# Docker Compose configuration for Shadiejo

services:
  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - shadiejo-network

  # Backend API
  backend:
    build: ./backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/shadiejo
    depends_on:
      - db
    volumes:
      - ./backend:/app
      - /app/__pycache__
    networks:
      - shadiejo-network

  # Frontend
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - shadiejo-network

volumes:
  postgres_data:

networks:
  shadiejo-network:
    driver: bridge
