"""Increase CNIC image column size

Revision ID: 5ea5a3ca8be7
Revises: 
Create Date: 2025-10-15 00:17:26.868064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ea5a3ca8be7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pending_vendor_verifications', 'cnic_front_image',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=1000000),
               existing_nullable=True)
    op.alter_column('pending_vendor_verifications', 'cnic_back_image',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=1000000),
               existing_nullable=True)
    op.alter_column('vendors', 'cnic_front_image',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=1000000),
               existing_nullable=True)
    op.alter_column('vendors', 'cnic_back_image',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=1000000),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vendors', 'cnic_back_image',
               existing_type=sa.String(length=1000000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.alter_column('vendors', 'cnic_front_image',
               existing_type=sa.String(length=1000000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.alter_column('pending_vendor_verifications', 'cnic_back_image',
               existing_type=sa.String(length=1000000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.alter_column('pending_vendor_verifications', 'cnic_front_image',
               existing_type=sa.String(length=1000000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    # ### end Alembic commands ###
